#!/bin/bash

DEBUG=$1

svn --version 2> /dev/null
if [ $? != 0 ]; then
  echo Please install subversion
  exit
fi

unzip -v 2> /dev/null
if [ $? != 0 ]; then
  echo Please install unzip
  exit
fi

python2 -V 2> /dev/null
if [ $? != 0 ]; then
  echo Please install python2
  exit
fi

set -e

ln -s `which python2` `pwd`/python
export PATH=`pwd`:$PATH

echo Build cjdns on OpenWRT
mkdir -p `pwd`/cjdowrt-build
pushd `pwd`/cjdowrt-build
  svn co svn://svn.openwrt.org/openwrt/trunk/ openwrt
  cd openwrt
  cp ./feeds.conf.default ./feeds.conf 
  echo 'src-git cjdns git://github.com/cjdelisle/cjdns-openwrt.git' >> ./feeds.conf
  ./scripts/feeds update -a
  ./scripts/feeds install cjdns
  make menuconfig $DEBUG
  make defconfig $DEBUG
  make $DEBUG
popd
